/* Supabase browser sync. The publishable key is intended to be public; protect data with RLS. */
(()=>{'use strict';
const URL='https://xpptebgwfiunequteqnv.supabase.co';
const KEY='sb_publishable_riprzt4q63TFdBQSUy6HgQ_DpqaFbN-';
const DATA_KEY='lrx_state_v140',SESSION_KEY='lrx_supabase_session_v1';
const RESOURCE_BUCKET='lrx-resources';
let session=null,revision=null,lastSynced='',pollTimer=null,publishTimer=null,busy=false,conflict=false,syncReady=false;
const statusEl=()=>document.getElementById('syncStatus');
function status(label,kind='local'){const el=statusEl();if(!el)return;el.querySelector('b').textContent=label;el.dataset.state=kind;el.title=kind==='cloud'?'Datos sincronizados en la nube':kind==='error'?'No se pudo sincronizar; los cambios siguen guardados en este dispositivo':'Sincroniza los registros entre tus dispositivos';}
function syncErrorMessage(error){return error?.name==='QuotaExceededError'?'Safari no tiene espacio suficiente para guardar la combinación en este dispositivo. Esta vez no se publicó ningún cambio nuevo en la nube. Cancela el aviso y no reemplaces ninguna copia; primero hay que liberar espacio o preparar otro método de sincronización.':error?.message||'No se pudo conectar con Supabase. Los datos siguen guardados en este dispositivo.'}
function localState(){try{return JSON.parse(localStorage.getItem(DATA_KEY)||'{}')}catch{return{}}}
function stableJSON(value){if(Array.isArray(value))return '['+value.map(stableJSON).join(',')+']';if(value&&typeof value==='object'){return '{'+Object.keys(value).sort().filter(key=>value[key]!==undefined).map(key=>JSON.stringify(key)+':'+stableJSON(value[key])).join(',')+'}'}return JSON.stringify(value)}
async function saveLocal(value){const next=JSON.stringify(value),backupKey=DATA_KEY+'.backup';try{const previous=localStorage.getItem(DATA_KEY);if(previous&&previous!==next)localStorage.setItem(backupKey,JSON.stringify({savedAt:new Date().toISOString(),state:JSON.parse(previous)}))}catch(error){console.warn('LRX pre-sync backup skipped',error)}localStorage.setItem(DATA_KEY,next);if(window.LRXPersistentState)await window.LRXPersistentState.flush()}
function request(path,options={}){const headers={apikey:KEY,'Content-Type':'application/json',...(options.headers||{})};if(session?.access_token)headers.Authorization='Bearer '+session.access_token;return fetch(URL+path,{...options,headers});}
async function refresh(){if(!session?.refresh_token)return false;const r=await fetch(URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){session=null;localStorage.removeItem(SESSION_KEY);return false}session=await r.json();localStorage.setItem(SESSION_KEY,JSON.stringify(session));return true}
async function authorized(path,options){let r=await request(path,options);if(r.status===401&&await refresh())r=await request(path,options);return r}
async function uploadResourceFile(file,resourceId){if(!session?.access_token)throw Error('Conecta esta app con Supabase antes de subir documentos.');const safeName=String(file.name||'documento').normalize('NFKD').replace(/[^\w.-]+/g,'_').slice(-120)||'documento',ext=safeName.split('.').pop().toLowerCase(),mime=file.type&&file.type!=='application/octet-stream'?file.type:({pdf:'application/pdf',txt:'text/plain',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}[ext]||'application/octet-stream'),path=`resources/${String(resourceId).replace(/[^\w-]/g,'_')}/${Date.now()}-${safeName}`,encoded=path.split('/').map(encodeURIComponent).join('/'),r=await authorized('/storage/v1/object/'+RESOURCE_BUCKET+'/'+encoded,{method:'POST',headers:{'Content-Type':mime,'x-upsert':'false'},body:file});if(!r.ok)throw Error('No se pudo guardar el documento en Supabase Storage: '+await r.text());return {path,name:file.name||safeName,type:mime,size:file.size||0,uploadedAt:new Date().toISOString()}}
async function downloadResourceFile(path){if(!session?.access_token)throw Error('Inicia sesión y conecta Supabase para leer el documento.');const encoded=String(path||'').split('/').map(encodeURIComponent).join('/'),r=await authorized('/storage/v1/object/authenticated/'+RESOURCE_BUCKET+'/'+encoded,{method:'GET',headers:{}});if(!r.ok)throw Error('No se pudo leer el documento ('+r.status+').');return r.blob()}
async function getCloud(){const r=await authorized('/rest/v1/lrx_app_state?id=eq.main&select=id,payload,revision',{method:'GET'});if(!r.ok)throw Error('Lectura Supabase '+r.status+': '+await r.text());return (await r.json())[0]||null}
async function uploadInitial(payload){const r=await authorized('/rest/v1/lrx_app_state',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id:'main',payload,revision:1,updated_by:session.user?.id||null})});if(!r.ok)throw Error('No se pudo iniciar la copia compartida: '+await r.text());const rows=await r.json();revision=rows[0]?.revision||1;lastSynced=stableJSON(payload);}
function hasRecords(s){return Object.entries(s||{}).some(([key,value])=>key!=='users'&&key!=='audit'&&Array.isArray(value)&&value.length>0)}
async function login(){const form=document.createElement('form');form.innerHTML='<div style="position:fixed;inset:0;z-index:30000;background:#10182888;display:grid;place-items:center;padding:18px"><div style="background:white;color:#182235;width:min(440px,100%);padding:24px;border-radius:18px;box-shadow:0 18px 70px #0005"><h2 style="margin:0 0 8px">Conectar dispositivos</h2><p>Inicia sesión con tu cuenta autorizada de LRX.</p><label style="display:block;margin:14px 0 6px">Correo</label><input name="email" type="email" autocomplete="username" required style="box-sizing:border-box;width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:9px"><label style="display:block;margin:14px 0 6px">Contraseña</label><input name="password" type="password" autocomplete="current-password" required style="box-sizing:border-box;width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:9px"><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:20px"><button type="button" data-cancel style="padding:10px 16px">Cancelar</button><button type="submit" style="padding:10px 16px;background:#c92d70;color:white;border:0;border-radius:8px">Continuar</button></div></div></div>';document.body.append(form);const credentials=await new Promise(resolve=>{form.addEventListener('submit',e=>{e.preventDefault();resolve({email:form.elements.email.value.trim(),password:form.elements.password.value})},{once:true});form.querySelector('[data-cancel]').onclick=()=>resolve(null)});form.remove();if(!credentials)return;status('Conectando…','local');const r=await fetch(URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(credentials)});if(!r.ok)throw Error('No se pudo iniciar sesión. Revisa el correo, contraseña y que la base de Supabase esté activa.');session=await r.json();localStorage.setItem(SESSION_KEY,JSON.stringify(session));await connect(true)}
async function connect(isFirst=false){if(!session)return;if(window.LRXPersistentState?.ready)await window.LRXPersistentState.ready;const cloud=await getCloud(),local=localState();if(!cloud){if(!hasRecords(local)){status('Esperando copia inicial','error');alert('La nube todavía no tiene datos. Primero inicia sesión en el dispositivo que contiene tus registros y elige subirlos. Después conecta los demás dispositivos.');return}if(confirm('La nube todavía no tiene registros. ¿Quieres subir ahora los registros de este dispositivo para compartirlos con tus socios?')){await uploadInitial(local);syncReady=true;status('Sincronizado','cloud');startPolling()}else{status('Sin nube configurada','local')}return}
 revision=Number(cloud.revision)||1;const cloudText=stableJSON(cloud.payload||{}),localText=stableJSON(local);
 if(!lastSynced){if(localText===cloudText){lastSynced=cloudText;status('Sincronizado','cloud')}else if(hasRecords(local)){const choice=await chooseConflictResolution();if(!choice){status('Revisa la copia de datos','error');return}if(choice==='cloud'){preserveLocalBeforeReplace(local);await saveLocal(cloud.payload||{});lastSynced=cloudText;status('Sincronizado','cloud');location.reload();return}if(choice==='local'){await replaceCloud(local);status('Sincronizado','cloud')}else{const merged=mergeValues(local,cloud.payload||{});await saveLocal(merged);await replaceCloud(merged);lastSynced=stableJSON(merged);status('Sincronizado','cloud');location.reload();return}}else{await saveLocal(cloud.payload||{});lastSynced=cloudText;status('Sincronizado','cloud');location.reload()}}
 else if(localText===lastSynced&&cloudText!==lastSynced){await saveLocal(cloud.payload||{});revision=cloud.revision;lastSynced=cloudText;status('Sincronizado','cloud');location.reload()}else if(localText!==cloudText){conflict=true;status('Conflicto: toca para revisar','error')}else{lastSynced=cloudText;status('Sincronizado','cloud')}
 syncReady=true;startPolling();
}
function startPolling(){if(!pollTimer)pollTimer=setInterval(()=>poll().catch(e=>{console.warn('LRX cloud poll',e);status('Sin conexión; guardado local','error')}),12000)}
async function replaceCloud(payload){const r=await authorized('/rest/v1/lrx_app_state?id=eq.main&revision=eq.'+revision,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({payload,revision:revision+1,updated_by:session.user?.id||null})});if(!r.ok)throw Error('No se pudo actualizar la copia compartida: '+await r.text());const rows=await r.json();if(!rows.length)throw Error('Otro dispositivo cambió los datos. Se conservaron los datos locales; vuelve a tocar el estado para resolver el conflicto.');revision++;lastSynced=stableJSON(payload);}
async function poll(){if(!session||!syncReady||busy)return;const cloud=await getCloud();if(!cloud)return;const cloudText=stableJSON(cloud.payload||{}),localText=stableJSON(localState());if(cloudText===lastSynced){revision=cloud.revision;return}if(localText===lastSynced){await saveLocal(cloud.payload||{});revision=cloud.revision;lastSynced=cloudText;status('Sincronizado','cloud');location.reload();return}conflict=true;status('Conflicto: toca para revisar','error')}
function onLocalSave(value){if(!session||!syncReady||conflict)return;clearTimeout(publishTimer);const snapshot=JSON.parse(JSON.stringify(value));publishTimer=setTimeout(async()=>{if(busy)return;busy=true;try{if(window.LRXPersistentState)await window.LRXPersistentState.flush();await replaceCloud(snapshot);status('Sincronizado','cloud')}catch(e){console.error(e);conflict=true;status('Conflicto: toca para revisar','error')}finally{busy=false}},900)}
async function acceptInvite(){const params=new URLSearchParams(location.hash.slice(1));if(params.get('type')!=='invite'||!params.get('access_token'))return false;const access=params.get('access_token'),refreshToken=params.get('refresh_token')||'';history.replaceState(null,'',location.pathname+location.search);const form=document.createElement('form');form.innerHTML='<div style="position:fixed;inset:0;z-index:30000;background:#10182888;display:grid;place-items:center;padding:18px"><div style="background:white;color:#182235;width:min(440px,100%);padding:24px;border-radius:18px;box-shadow:0 18px 70px #0005"><h2>Activa tu acceso a LRX</h2><p>Crea una contraseña para iniciar sesión en tus dispositivos.</p><label style="display:block;margin:14px 0 6px">Nueva contraseña</label><input name="password" type="password" autocomplete="new-password" minlength="8" required style="box-sizing:border-box;width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:9px"><label style="display:block;margin:14px 0 6px">Confirma la contraseña</label><input name="confirm" type="password" autocomplete="new-password" minlength="8" required style="box-sizing:border-box;width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:9px"><div style="display:flex;justify-content:flex-end;margin-top:20px"><button type="submit" style="padding:10px 16px;background:#c92d70;color:white;border:0;border-radius:8px">Guardar contraseña</button></div></div></div>';document.body.append(form);await new Promise(resolve=>form.addEventListener('submit',async e=>{e.preventDefault();const password=form.elements.password.value;if(password!==form.elements.confirm.value){alert('Las contraseñas no coinciden.');return}const button=form.querySelector('button');button.disabled=true;try{const r=await fetch(URL+'/auth/v1/user',{method:'PUT',headers:{apikey:KEY,Authorization:'Bearer '+access,'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw Error('No se pudo activar la cuenta. El enlace puede haber vencido; solicita una nueva invitación.');const user=await r.json();session={access_token:access,refresh_token:refreshToken,token_type:'bearer',user};localStorage.setItem(SESSION_KEY,JSON.stringify(session));form.remove();await connect(true);resolve()}catch(error){button.disabled=false;alert(error.message||'No se pudo activar la cuenta.')}},{once:false}));return true}
function mergeValues(local,cloud){
 if(Array.isArray(local)||Array.isArray(cloud)){
  const left=Array.isArray(local)?local:[],right=Array.isArray(cloud)?cloud:[],out=[],positions=new Map();
  const keyOf=value=>value&&typeof value==='object'&&!Array.isArray(value)?String(value.id??value.uuid??value.key??value.code??value.name??JSON.stringify(value)):JSON.stringify(value);
  for(const item of [...right,...left]){const key=keyOf(item);if(!positions.has(key)){positions.set(key,out.length);out.push(item);continue}const at=positions.get(key),existing=out[at];if(item&&existing&&typeof item==='object'&&typeof existing==='object'&&!Array.isArray(item)&&!Array.isArray(existing))out[at]=mergeValues(item,existing)}
  return out;
 }
 if(local&&cloud&&typeof local==='object'&&typeof cloud==='object'){
  const localTime=Date.parse(local.updatedAt||local.modifiedAt||''),cloudTime=Date.parse(cloud.updatedAt||cloud.modifiedAt||''),preferred=Number.isFinite(localTime)&&localTime>cloudTime?local:cloud,other=preferred===local?cloud:local,out={...other,...preferred};
  for(const key of new Set([...Object.keys(local),...Object.keys(cloud)]))if(local[key]&&cloud[key]&&typeof local[key]==='object'&&typeof cloud[key]==='object')out[key]=mergeValues(local[key],cloud[key]);
  return out;
 }
 return local===undefined?cloud:cloud===undefined?local:cloud;
}
function chooseConflictResolution(){return new Promise(resolve=>{const layer=document.createElement('div');layer.style.cssText='position:fixed;inset:0;z-index:31000;background:#10182899;display:grid;place-items:center;padding:18px';layer.innerHTML='<div style="background:#fff;color:#182235;width:min(480px,100%);padding:22px;border-radius:16px;box-shadow:0 18px 70px #0005"><h2 style="margin:0 0 8px">Hay dos copias de los datos</h2><p style="line-height:1.5">Combinar conserva los registros de este dispositivo y de la nube. Si un mismo registro cambió en ambas copias, se conserva la versión más reciente; los registros eliminados podrían reaparecer para evitar perderlos.</p><div style="display:grid;gap:9px;margin-top:18px"><button data-choice="merge" style="padding:12px;background:#c92d70;color:white;border:0;border-radius:9px;font-weight:700">Combinar ambas copias</button><button data-choice="cloud" style="padding:11px;background:white;border:1px solid #cbd5e1;border-radius:9px">Usar la copia de la nube</button><button data-choice="local" style="padding:11px;background:white;border:1px solid #cbd5e1;border-radius:9px">Publicar la copia de este dispositivo</button><button data-choice="cancel" style="padding:9px;background:transparent;border:0">Cancelar</button></div></div>';layer.addEventListener('click',event=>{const choice=event.target.closest('[data-choice]')?.dataset.choice;if(!choice)return;layer.remove();resolve(choice==='cancel'?null:choice)});document.body.append(layer)})}
function preserveLocalBeforeReplace(value){try{localStorage.setItem(DATA_KEY+'.backup',JSON.stringify({savedAt:new Date().toISOString(),state:value}))}catch(error){console.warn('LRX local pre-sync backup unavailable',error)}}
async function handle(){try{if(!session){await login();return}if(conflict){const cloud=await getCloud();if(!cloud)throw Error('No se encontró la copia de la nube.');revision=Number(cloud.revision)||1;const cloudPayload=cloud.payload||{},choice=await chooseConflictResolution();if(!choice)return;if(choice==='cloud'){const local=localState();preserveLocalBeforeReplace(local);await saveLocal(cloudPayload);lastSynced=stableJSON(cloudPayload);conflict=false;status('Sincronizado','cloud');location.reload();return}if(choice==='local'){await replaceCloud(localState());conflict=false;status('Sincronizado','cloud');startPolling();return}const local=localState(),merged=mergeValues(local,cloudPayload);await saveLocal(merged);await replaceCloud(merged);lastSynced=stableJSON(merged);conflict=false;status('Sincronizado','cloud');location.reload();return}await connect(false)}catch(e){console.error('LRX cloud sync',e);status('Error de conexión','error');alert(syncErrorMessage(e))}}
try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{session=null}
window.LRXCloudSync={onLocalSave,uploadResourceFile,downloadResourceFile};document.addEventListener('DOMContentLoaded',async()=>{status(session?'Conectando…':'Solo en este dispositivo','local');statusEl()?.addEventListener('click',handle);if(await acceptInvite())return;if(session)setTimeout(()=>connect(false).catch(e=>{console.error(e);status('Error de conexión','error');alert(syncErrorMessage(e))}),1800)});
})();
